###(If you are using Google Colab) then you must first connect your Google Colab Notebook to Google Drive folder.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Second step is to bring in the relevant libraries for ETL work: pandas and numpy

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
insurance_data_table = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/insurance.csv")

In [ ]:
insurance_data_table.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
age_column = insurance_data_table["age"]
age_column.head()

0    19
1    18
2    28
3    33
4    32
Name: age, dtype: int64